site_name: Tomas | Projects & Study Notes
site_description: Electronics, coding projects, and study notes
site_url: https://Tomas-Gradowski.github.io/portifolio
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
  - Study Notes:
      - Advanced Quantum Mechanics: "notes/Advanced Quantum Mechanics/index.md"
      - Asymptotic Statistics: "notes/Asymptotic Statistics/index.md"
      - Convex Optimization: "notes/Convex/index.md"
      - High Energy Physics: "notes/High Energy Physics/index.md"
      - Solid Mechanics: "notes/Solid Mechanics/index.md"
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
repo_url: https://github.com/Tomas-Gradowski/portifolio
repo_name: GitHub
edit_uri: edit/main/docs/
